[project]
authors = ["Philip Patton <pattonp@hawaii.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "autocapture"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
